connect:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: yt_lounge
          domain: media_player

get_now_playing:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: yt_lounge
          domain: media_player

get_video_details:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: yt_lounge
          domain: media_player
    video_id:
      required: true
      selector:
        text:

subscribe:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: yt_lounge
          domain: media_player

raw_command:
  fields:
    entity_id:
      required: true
      selector:
        entity:
          integration: yt_lounge
          domain: media_player
    command:
      required: true
      selector:
        text:
    args:
      required: false
      selector:
        object:
